apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstack-ingress
  namespace: localstack
spec:
  ingressClassName: nginx
  rules:
    - host: milocalstack.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: op-localstack
                port:
                  number: 4566